defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_prepper:
  active: False
  redcap_database: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/L1958Narco_DATA_2024-01-31_1014.csv"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"

data_sorter:
  active: True
  input_file: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes/complete_dataframe.csv"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"
