defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_prepper:
  active: False
  redcap_database: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/L1958Narco_DATA_2024-02-07_1349.csv"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"

data_sorter:
  active: False
  input_file: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes/complete_dataframe.xlsx"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"

first_analysis:
  active: True
  input_file: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes/complete_dataframe.xlsx"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"
  
  high_take_off: 10
  acute_take_off: 45
  slit_like_ostium_ratio: 2.5
  percent_stenosis: 0.5
  elliptic_ratio: 1.3
  percent_hypoplasia: 0.5
  imc_length_cutoff: 0 

demographics:
  dict_variables: 
    # demographics
    - "record_id"
    - "age"
    - "bmi"
    - "sex_0_male_1_female"
    # diagnostic tools
    - "dgn_diagtool___0"
    - "dgn_diagtool___1"
    - "dgn_diagtool___5"
    - "dgn_diagtool___8"
    - "dgn_echo_ef"
    - "dgn_echo_wma"
    - "dgn_echo_diafun"
    - "dgn_ecg_classification"
  
  output_dir_data: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/statistical_analysis/data"
  output_dir_figures: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/statistical_analysis/figures"

  dict_rename: 
    sex_0_male_1_female: sex_0_male_1_female
    age: age
    bmi: bmi
    hx_caa_known: hx_caa_known
    hx_init_none: hx_init_pres_type___0
    hx_init_angina: hx_init_pres_type___1
    hx_init_syncope: hx_init_pres_type___2
    hx_init_dyspnea: hx_init_pres_type___3
    hx_init_palpitations: hx_init_pres_type___4
    hx_init_presyncope: hx_init_pres_type___5
    hx_init_fatigue: hx_init_pres_type___6
    hx_init_arrythmia: hx_init_pres_type___7
    hx_init_gi_symptoms: hx_init_pres_type___8
    hx_init_mi: hx_init_pres_type___9
    hx_init_scd: hx_init_pres_type___10
    hx_init_aborted_scd: hx_init_pres_type___11
    hx_init_other: hx_init_pres_type___12
    hx_sym_ap: hx_sym_ap
    hx_sym_ap_ccs: hx_sym_ap_ccs
    hx_sym_ap_stress: hx_sym_ap_stress
    hx_sym_sync_exercise: hx_sym_sync_exercise
    hx_sym_dysp_nyha: hx_sym_dysp_nyha
    hx_sym_div_exercise: hx_sym_div_exercise
    hx_htn: hx_htn
    hx_dm: hx_dm
    hx_chol: hx_chol
    hx_fhx_cad: hx_fhx___1
    hx_fhx_caa: hx_fhx___2
    hx_fhx_scd: hx_fhx___3
    hx_fhx_otherheart: hx_fhx___4
    hx_fhx_none: hx_fhx___0
    hx_hxtobacco: hx_hxtobacco
    hx_bm_asp: hx_bm_asp
    hx_bm_statin: hx_bm_statin
    hx_bm_clopi: hx_bm_clopi
    hx_bm_ticagrelor: hx_bm_ticagrelor
    hx_bm_prasugrel: hx_bm_prasugrel
    hx_bm_calcblock: hx_bm_calcblock
    hx_bm_betablock: hx_bm_betablock
    hx_bm_nitrates: hx_bm_nitrates
    hx_bm_noak: hx_bm_noak
    hx_bm_antico: hx_bm_antico
    hx_bm_ace: hx_bm_ace
    hx_bm_arb: hx_bm_arb
    hx_bm_diuretic: hx_bm_diuretic
    sports_yn: sports_yn
    sports_level: sports_level
    sports_static_component: sports_static_component
    sports_dynamic_component: sports_dynamic_component
    sports_symptoms: sports_symptoms
    sports_yn_ch: sports_yn_ch
    sports_ch_symp: sports_ch_symp
    sports_level_ch: sports_level_ch
    sports_static_component_ch: sports_static_component_ch
    sports_dynamic_comp_ch: sports_dynamic_comp_ch
    caa_modality: caa_modality
    caa_raaoca: caa_origin___0
    caa_ladaaoca: caa_origin___1
    caa_lmaaoca: caa_origin___2
    caa_singleright: caa_origin___3
    caa_singleleft: caa_origin___4
    caa_cxaaoca: caa_origin___5
    caa_other: caa_origin___6
    caa_ostia: caa_ostia
    caa_interarterial: caa_course___0
    caa_subpulmonic: caa_course___1
    caa_prepulmonic: caa_course___2
    caa_retroaortic: caa_course___3
    caa_retrocardiac: caa_course___4
    caa_othercourse: caa_course___5
    caa_high_rca: caa_high_coronary___0
    caa_high_lca: caa_high_coronary___1
    caa_slo: caa_slo
    caa_elliptic: caa_elliptic
    caa_pn: caa_pn
    caa_angle: caa_angle
    caa_im: caa_im
    caa_malignancy: caa_malignancy
    dgn_diagtool___1: dgn_diagtool___1
    dgn_echo_ef: dgn_echo_ef
    dgn_echo_wma: dgn_echo_wma
    dgn_echo_diafun: dgn_echo_diafun
    ccta_photon: ccta_photon
    ccta_quali: ccta_quali
    ccta_ostial_a: ccta_ostial_a
    ccta_ostial_h: ccta_ostial_h
    ccta_ostial_w: ccta_ostial_w
    ccta_mla_a: ccta_mla_a
    ccta_aa_degree: ccta_aa_degree
    ccta_imc_length: ccta_imc_length
    ccta_mla_elliptic: ccta_mla_elliptic
    ccta_pn_dist: ccta_pn_dist
    ccta_agatston: ccta_agatston
    ccta_dominance: ccta_dominance
    ccta_cad: ccta_cad
    funct_type___0: funct_type___0
    funct_ergo_findings: funct_ergo_findings
    inv_dominance: inv_dominance
    inv_cad: inv_cad
    inv_rest_hr: inv_rest_hr
    inv_rest_aosys: inv_rest_aosys
    inv_rest_aodia: inv_rest_aodia
    inv_rest_aomean: inv_rest_aomean
    inv_ffrado: inv_ffrado
    inv_ivusrest_mla: inv_ivusrest_mla
    inv_ffrdobu: inv_ffrdobu
    inv_ffrdobu_symp: inv_ffrdobu_symp
    inv_dobu_hr: inv_dobu_hr
    inv_dobu_aosys: inv_dobu_aosys
    inv_dobu_aodia: inv_dobu_aodia
    inv_dobu_aomean: inv_dobu_aomean
    inv_ivusdobu_mla: inv_ivusdobu_mla
    synp_inv: synp_inv
    synp_inv_yn: synp_inv_yn
    synp_funct: synp_funct
    synp_funct_yn: synp_funct_yn
    synp_hemo: synp_hemo
    synp_symp: synp_symp
    synp_surgery: synp_surgery
    synp_surgery_yn: synp_surgery_yn
    synp_stent: synp_stent
    synp_stent_yn: synp_stent_yn
    synp_sport: synp_sport
    synp_treatment: synp_treatment