defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_prepper:
  active: False
  redcap_database: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/L1958Narco_DATA_2024-02-05_1506.csv"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"

data_sorter:
  active: False
  input_file: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes/complete_dataframe.xlsx"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"

first_analysis:
  active: True
  input_file: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes/complete_dataframe.xlsx"
  output_dir: "C:/WorkingData/Documents/2_Coding/Python/NARCO_analysis/dataframes"
  
  high_take_off: 10
  acute_take_off: 45
  slit_like_ostium_ratio: 2.5
  percent_stenosis: 0.5
  elliptic_ratio: 1.3
  percent_hypoplasia: 0.5
  imc_length_cutoff: 0 
